export const rolePermissions = {
  SuperAdmin: ["*"],
  OrgAdmin: [
    "dashboard.*",
    "teams.*",
    "players.*",
    "matches.*",
    "analytics.*",
    "billing.*",
    "admin.page.view",
    "admin.function.user.invite",
    "admin.function.user.disable",
    "admin.function.role.assign",
    "admin.function.audit.view",
    "profile.*"
  ],
  ManagerCoach: [
    "dashboard.*",
    "teams.page.view",
    "teams.card.roster.view",
    "teams.card.settings.view",
    "teams.function.create",
    "teams.function.update",
    "teams.function.member.add",
    "teams.function.member.remove",
    "players.page.view",
    "players.card.profile.view",
    "players.card.performance.view",
    "players.function.create",
    "players.function.update",
    "matches.page.view",
    "matches.card.schedule.view",
    "matches.card.result.view",
    "matches.function.create",
    "matches.function.result.submit",
    "analytics.page.view",
    "analytics.card.team.view",
    "analytics.card.player.view",
    "profile.*"
  ],
  Player: [
    "dashboard.page.view",
    "teams.page.view",
    "teams.card.roster.view",
    "players.page.view",
    "players.card.profile.view",
    "players.card.performance.view",
    "matches.page.view",
    "matches.card.schedule.view",
    "matches.card.result.view",
    "profile.*"
  ],
  Viewer: [
    "dashboard.page.view",
    "dashboard.card.kpi.view",
    "teams.page.view",
    "teams.card.roster.view",
    "players.page.view",
    "players.card.profile.view",
    "matches.page.view",
    "matches.card.schedule.view",
    "matches.card.result.view",
    "analytics.page.view",
    "analytics.card.team.view"
  ]
};
